export AUTOM8D_JIRA_TOKEN='thetoken'
export AUTOM8D_JIRA_EMAIL='youremail'
export AUTOM8D_JIRA_SERVER='https://yourserver.atlassian.com'
export AUTOM8D_JIRA_PROJECT='thenameofthesecurityproject'
export AUTOM8D_JIRA_ISSUE_TYPE='thetypeofissuetocreate'